### ISSUE TITLE
CUDA Suport for penCV

### ISSUE THREAD

**Issue by blgnksy** [DrewNF/Build-Research-Envirorment-with-Tensorflow-OpenCV-Python#1]
What must be the beginning step for building OpenCV with Cuda support? If I compile OpenCV before CUDA installation does is suffer from CUDA? 

Best,

**Comment by DrewNF** [comment]
The best way to do it, is to first of all install CUDA and all the NVidia support libraries, than install OpenCV, otherwise it will not allow you to abilitate CUDA during the installation.

Bests

**Comment by blgnksy** [comment]
Thanks.

**Comment by DrewNF** [comment]
you're welcome!
